"""remove facility from reports

Revision ID: 29c7fa3ccba8
Revises: 7a54caee85e0
Create Date: 2025-11-02 14:35:05.413063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29c7fa3ccba8'
down_revision = '7a54caee85e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('facility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
