"""Add course column to user and signup_request

Revision ID: 5475a0865d1d
Revises: 0fb9fbfbfcee
Create Date: 2025-11-05 19:17:16.958029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5475a0865d1d'
down_revision = '0fb9fbfbfcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('cp')

    with op.batch_alter_table('signup_requests', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
