"""add user_id to reports

Revision ID: 7a54caee85e0
Revises: e175bb13ab8b
Create Date: 2025-10-12 21:48:16.269983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a54caee85e0'
down_revision = 'e175bb13ab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('facility', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
