"""remove facility from reports

Revision ID: 8a21dca41aca
Revises: 29c7fa3ccba8
Create Date: 2025-11-02 14:41:17.383197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a21dca41aca'
down_revision = '29c7fa3ccba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_report', schema=None) as batch_op:
        batch_op.drop_column('facility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility', mysql.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
