"""add photo column to user and signup_request

Revision ID: baa8e2fdd7b7
Revises: 482339029a9a
Create Date: 2025-11-03 12:50:10.896098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa8e2fdd7b7'
down_revision = '482339029a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('signup_requests', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
